name: snap_bounty
version: 0.1.1
description: Photography Game utilizing Firebase and ML Kit
author: Connor Beardsmore <connor.beardsmore@gmail.com>
homepage: https://cbeardsmore.github.io
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.2
  carousel_pro: 0.0.13
  firebase_core: 0.4.0
  cloud_firestore: 0.12.1
  firebase_auth: 0.11.1
  google_sign_in: 4.0.1
  flutter_facebook_login: 2.0.1
  image_picker: 0.6.0
  firebase_ml_vision: 0.8.0
  cached_network_image: 0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/
