name: snap_hero
description: Photography Game utilizing Firebase and ML Kit

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.2
  firebase_core: 0.3.1+1
  cloud_firestore: 0.9.11
  firebase_auth: 0.8.4
  google_sign_in: 4.0.1
  flutter_facebook_login: 2.0.0
  image_picker: 0.5.3
  firebase_ml_vision: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/
