version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      
      - run: 
          name: Flutter Doctor
          command: flutter doctor

      - run: 
          name: Create Build Version
          command: |
            .circleci/version.sh >> /tmp/.version
            echo Build Version: `cat /tmp/.version`
            echo Build Number: $CIRCLE_BUILD_NUM

      - run:
          name: Android Keystore Setup
          command: .circleci/keystore.sh

      - run: 
          name: Flutter Build APK
          command: |
            VERSION=$(cat /tmp/.version)
            flutter build apk --build-name=$VERSION --build-number=$CIRCLE_BUILD_NUM

      - store_artifacts:
          path: ./build/app/outputs/apk/release/app-release.apk
          destination: .apk/snaphero.apk
          
workflows:
  version: 2
  build-n-publish:
    jobs:
    - build:
        filters:
          tags:
            only: /^v.*/